name: Merge PRs
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@c9bd1823770819dc8fb8a5db2d11a3a95fbe9b07"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "approved,!work-in-progress,!hold"
          MERGE_METHOD: "rebase"
          MERGE_DELETE_BRANCH: "true"

      - uses: octokit/request-action@v2.x
        id: get_pullrequest
        with:
          route: GET /repos/:repository/pulls/:pr_number
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: start deployment
        if: fromJson(steps.get_pullrequest.outputs.data).state == 'closed'
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: deploy
          ref: source
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
