name: build

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!source'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build
        run: |
          npm i
          npm run build-prod
