name: build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.46.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build-prod
